name: Deploy NestJS Docker Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Fazer login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar arquivo .env a partir das Secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Construir e publicar imagem Docker
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy Azure Web App (container) usando Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: mural-testemunhos
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 'ghcr.io/tasaboia/mural-testemunhos:${{ github.sha }}'
 